export const AUDIT_EVENTS = {
  JOTFORM_SUBMISSION_RECEIVED: 'JOTFORM_SUBMISSION_RECEIVED',
  VOG_VALIDATED: 'VOG_VALIDATED',
  CONTRACT_SIGNED: 'CONTRACT_SIGNED',
  STEP_UPDATED: 'STEP_UPDATED',
} as const;